// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortBy } from "./SortBy";

export type SearchQuery = { bodyTerms: Array<string>, negatedBodyTerms: Array<string>, tagFilters: Array<string>, negatedTagFilters: Array<string>, nameFilter: string | null, negatedNameFilter: string | null, sortBy: SortBy, pinnedFirst: boolean, };
