// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncProvider } from "./SyncProvider";

export type Settings = { reverseLayout: boolean, syncProvider: SyncProvider, yandexOauthToken: string, };
